# Generated by Django 5.1 on 2024-09-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_balanca', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setor', models.CharField(max_length=100)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
